using QuestPDF.Fluent;
using QuestPDF.Infrastructure;

namespace Spectra.Api.Services;

// Shared page chrome (header/footer) and small building blocks reused by
// every report generator, so every report — Security, Users, and whatever
// comes next — looks consistent automatically rather than each copying the
// same layout code.
public static class ReportComponents
{
    public static void ComposeHeader(IContainer container, string reportTitle, string customerName, DateTimeOffset generatedAt)
    {
        container.Background(ReportTheme.CardBackground).BorderBottom(1).BorderColor(ReportTheme.CardBorder).Padding(28).Row(row =>
        {
            row.ConstantItem(40).Height(40).CornerRadius(12).BackgroundLinearGradient(220, ReportTheme.BrandGradientStops);

            row.RelativeItem().PaddingLeft(16).Column(column =>
            {
                column.Item().Text("Spectra").FontSize(18).SemiBold().FontColor(ReportTheme.TextPrimary);
                column.Item().Text(reportTitle).FontSize(11).FontColor(ReportTheme.TextSecondary);
            });

            row.ConstantItem(220).Column(column =>
            {
                column.Item().AlignRight().Text(customerName).FontSize(14).SemiBold().FontColor(ReportTheme.TextPrimary);
                column.Item().AlignRight().Text($"Generated {generatedAt.ToLocalTime():MMMM d, yyyy}").FontSize(9).FontColor(ReportTheme.TextTertiary);
            });
        });
    }

    public static void ComposeFooter(IContainer container)
    {
        container.BorderTop(1).BorderColor(ReportTheme.CardBorder).PaddingTop(10).Row(row =>
        {
            row.RelativeItem().Text("Generated by Spectra").FontSize(8).FontColor(ReportTheme.TextTertiary);
            row.RelativeItem().AlignRight().Text(x =>
            {
                x.DefaultTextStyle(s => s.FontSize(8).FontColor(ReportTheme.TextTertiary));
                x.Span("Page ");
                x.CurrentPageNumber();
                x.Span(" of ");
                x.TotalPages();
            });
        });
    }

    public static void SummaryTile(IContainer container, string label, string value)
    {
        container.Background(ReportTheme.CardBackground).Border(1).BorderColor(ReportTheme.CardBorder).CornerRadius(10).Padding(14).Column(column =>
        {
            column.Item().Text(label).FontSize(9).FontColor(ReportTheme.TextTertiary);
            column.Item().PaddingTop(4).Text(value).FontSize(18).SemiBold().FontColor(ReportTheme.TextPrimary);
        });
    }

    public static void StatusDot(IContainer container, string color)
    {
        container.Width(8).Height(8).AlignMiddle().Background(color).CornerRadius(4);
    }
}
