// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spectra.Api.Data;

#nullable disable

namespace Spectra.Api.Migrations
{
    [DbContext(typeof(SpectraDbContext))]
    [Migration("20260725231025_AddExoSecondBatchChecks")]
    partial class AddExoSecondBatchChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Spectra.Api.Data.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminGroupDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Spectra.Api.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBootstrapAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Spectra.Api.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionalAccessPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentGranted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoAcceptedDomainsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoAdminAuditLogConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoAntiPhishPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoDkimSigningConfigsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoHostedConnectionFilterPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoHostedContentFilterPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoHostedOutboundSpamFilterPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExoLastCollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoLastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoMalwareFilterPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoOrganizationConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExoRoleAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExoSafeAttachmentPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoSafeLinksPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoSharingPoliciesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExoTransportRulesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecureScoreControlProfilesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecureScoreJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Spectra.Api.Data.CustomerUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccountEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForwardingRulesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasArchiveMailbox")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InboxRulesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MailboxItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MailboxSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MfaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "GraphUserId")
                        .IsUnique();

                    b.ToTable("CustomerUsers");
                });

            modelBuilder.Entity("Spectra.Api.Data.DatabaseConnectionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsProvisioned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
